export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';


export const MAKE_USER_FAVORITE = 'MAKE_USER_FAVORITE';
export const POST_USER_CONTACT = 'POST_USER_CONTACT';
export const DELETE_USER_CONTACT = 'DELETE_USER_CONTACT';

export const FIND_USER = 'FIND_USER';
